artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: put-the-link/address-of-your-data
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion